### ISSUE TITLE
Some installation issues

### ISSUE THREAD

**Issue by Dafidofff** [tarungog/torsionnet_paper_version#1]
When creating the environment supplied with this directory, a ResolvePackageNotFound error pops up. Moreover, commands to install the customised agents doesn't correspond to the existing directories. Should be an under score instead.

**Comment by runxuanjiang** [comment]
Hello,

I believe the issue was because a few of the dependencies we used were of the wrong version.  I updated the code so that it works with all the latest versions of the dependencies and I also updated the environment.yml and installation instructions, so you should be able to install everything now.

I believe there are still some minor issues with the tchains experiment, but I tested all the other experiments, which includes all the custom models (neural networks), agents, and environments and they were able to run properly.

Please let me know if you run into any other issues.

**Comment by Dafidofff** [comment]
Dear Tarun Gogineni,

I forked the GitHub repo again so I could have a fresh start. However, I got the same ‘ResolvePackageNotFound' issue when creating the conda environment. I thought if found a solution by moving the libraries, for which the error occurs, underneath ‘-pip:’ within environment.yml. This still leads to a 'CondaEnvException: Pip failed’ exception. However, after installing some libraries such as deepchem, rdkit, etc.. in this conda environment I succeeded in running the code. I do not know why the env can’t be build from start, but friends of my experienced the same problem. 
I want to use TorsionNet as a baseline for my master thesis so thanks for replying to me, such that I can get the code to work. 

Kind regards,

David Wessels

**Comment by runxuanjiang** [comment]
Thanks for the follow-up David,

If you don't mind, could you tell me what OS you are using and which of the libraries failed to install from the '.yml' file? I was able to test the installation succesfully on both CentOS and Windows Subsystem for Linux (WSL) so I'm not sure if the problem is a platform-specific issue.

Thank you

**Comment by Dafidofff** [comment]
Hi,

I’m running macOS Big Sur 11.2.1, and below I posted a screenshot with the original error when creating the conda environment. I have conda 4.9.2 installed, using a 3.7.6 python version. I hope you find something useful. 

Kind regards,

David Wessels

**Comment by Dafidofff** [comment]
Hi, 

I had a questions about the Gibbs score used in TorsionNet and then especially about the normalising value Z0 and hoped you can help me with it. In the paper there is said that Z0 is determined by the Gibbs scores over a conformer set generated by Rdkit. However, tot calculate this Gibbs scores have a conformer set, you already need the Z0. So, my question is, how is this initial Z0 determined? I hope to hear from you, 

Kind regards,

David Wesselsd

**Comment by tarungog** [comment]
Hi, initial Z_0 is calculated via Gibbs score formula ignoring Z_0 term. In other words you can plug in Z_0 = 1
